-- begin BPMSAMPLES_TASK
alter table BPMSAMPLES_TASK add constraint FK_BPMSAMPLES_TASK_ON_INITIATOR foreign key (INITIATOR_ID) references SEC_USER(ID)^
alter table BPMSAMPLES_TASK add constraint FK_BPMSAMPLES_TASK_ON_EXECUTOR foreign key (EXECUTOR_ID) references SEC_USER(ID)^
create index IDX_BPMSAMPLES_TASK_ON_INITIATOR on BPMSAMPLES_TASK (INITIATOR_ID)^
create index IDX_BPMSAMPLES_TASK_ON_EXECUTOR on BPMSAMPLES_TASK (EXECUTOR_ID)^
-- end BPMSAMPLES_TASK
